spring.application.name=ApexLegendsAPI

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

server.forward-headers-strategy=native
server.servlet.session.cookie.same-site=none
server.servlet.session.cookie.secure=true
logging.level.org.springframework.security=DEBUG

#server.servlet.session.cookie.same-site=none
#server.servlet.session.cookie.secure=true

#spring.profiles.active=local


